// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOnobdcEFQlyE_kNfAPZ9xpQyA1mW_PDg',
    appId: '1:435371774586:web:84db69de7980553b64e1c3',
    messagingSenderId: '435371774586',
    projectId: 'test1-9fef5',
    authDomain: 'test1-9fef5.firebaseapp.com',
    storageBucket: 'test1-9fef5.firebasestorage.app',
    measurementId: 'G-01598HFE9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKLFD56OtCxXL5wD4kq1Pi3SMOy7GFsLw',
    appId: '1:435371774586:android:fbed10be4407ab6464e1c3',
    messagingSenderId: '435371774586',
    projectId: 'test1-9fef5',
    storageBucket: 'test1-9fef5.firebasestorage.app',
  );
}
